# Cloudflare Pages Configuration
# ALSOK Interview System - Client Demo

name = "alsok-interview-demo"
compatibility_date = "2023-12-01"

[env.production]
# Cloudflare Pages環境変数（必要に応じて設定）

# Build Configuration
# Cloudflare Pagesは静的サイトのため、特別なビルドコマンドは不要
# すべてのHTML, CSS, JSファイルがそのままデプロイされます

# 推奨設定:
# Build command: (なし - 静的ファイル)
# Build output directory: / (root)
# Root directory: / (root)

# Environment Variables (Cloudflare Pages Dashboard で設定)
# CLIENT_DEMO_GAS_URL = "https://script.google.com/macros/s/AKfycbyZchii9FU-zsSWw-oLrTNAUkAI4MU8sqlEInRyA0c5kpxvsYGbjf_TtWqNrQeaHXBv/exec"